### ISSUE TITLE
As a developer, before I read and write data from the database, I need the get endpoint built.

### ISSUE THREAD

**Issue by mrnbanzon** [sumptingeneric/barback#19]

**Comment by deduced** [comment]
API documentation: https://barback.docs.apiary.io/# and will also be added to the project as a .apib file which follows the API Blueprint (https://apiblueprint.org/) format.

**Comment by deduced** [comment]
Endpoints created in express and respond with dummy data with an accurate shape. Remaining: wire up to the db models
