### ISSUE TITLE
Define end points/routes/ and data views

### ISSUE THREAD

**Issue by fredricklou523** [sumptingeneric/barback#26]

**Comment by deduced** [comment]
Endpoints: https://barback.docs.apiary.io/#

Routes will be defined in React and will correspond to the attached png files: 
1. admin_barman_routes.png 
2. customer_view_routes.png
![admin_barman_routes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b8f01ee10a5c500128d240f/125516c66e82c728ace21e0d46e990972a8cbcab8efbb242aa62e29b3c5222606b48e13b628ae92dbc56395b4d5a1ca417595a47f5fc8e7ef5e43c708a5e0dedd86e5d76c42f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e48d8d473b1a001180ff5c27ed.png)
![customer_view_routes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b8f01ee10a5c500128d240f/125516c66e82c728ace21e0d46eb8189378d8eac9dd6a94aa14acf86265333763a46ef696097ec22ba416f43554d4bfe490e5e41fff08c2cf3e56e708a5c09ebd1645c76c43f03b0aac04ee155e57dd205d0f4ae805ec1e03724e288894d361b011d80f65c34b2d4.png)
