### ISSUE TITLE
As a developer, I should not be able to push to the master branch directly

### ISSUE THREAD

**Issue by fredricklou523** [sumptingeneric/barback#27]

**Comment by deduced** [comment]
I may be missing something, but it seems that the protection is to only allow a single person to push to the master branch directly. In that case, I think that so long as we have forked the repo and working from there, we have enough controls as nobody will be able to "accidentally" push to the organization repo master so long as they did not clone the organization repo directly. 

My suggestion is to not do anything additional. We can keep the rule you defined whereby we need 3 sign-offs. What do you guys think?

**Comment by fredricklou523** [comment]
haha yeah I noticed the same, I added Michael as the sole Master Pusher for our group, I think if anything it can prevent accidents?  I don't think we'll have much to push to master once our environment is settled.  Open for discussion tomorrow morning!
